# Generated by Django 4.0.6 on 2022-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wstuser',
            name='validate',
            field=models.BooleanField(),
        ),
    ]
